### ISSUE TITLE
SSL cert verify failed

### ISSUE THREAD

**Issue by westlakem** [titusfortner/webdrivers#1]
C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:852:in `start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:319:in `open_http'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/webdrivers-2.4.0/lib/webdrivers/geckodriver.rb:26:in `downloads'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/webdrivers-2.4.0/lib/webdrivers/geckodriver.rb:17:in `newest_version

**Comment by kapoorlakshya** [comment]
I am getting the same error. I even updated the SSL certs and that did not work. Surprisingly, I only got this error once. I am now receiving this error:

> unable to connect to Mozilla geckodriver 127.0.0.1:4444 (Selenium::WebDriver::Error::WebDriverError)

The reason is because the geckodriver.exe is not available in the ~/.webdrivers folder. @titusfortner, any idea idea why? Chrome and IE work fine.
