### ISSUE TITLE
Configuring headless chrome

### ISSUE THREAD

**Issue by BSierakowski** [titusfortner/webdrivers#119]
#### Summary
Sorry if this is obvious or already covered, but I'm switching over to this gem and find that my non-headless chrome tests work great, but the headless tests seem to pass, but don't move to the next test without a timeout. Is there a config I'm missing out on?

Let me know if this a "me" thing :). 

#### Debug Info
I've registered the driver like this: 
```
Capybara.register_driver :headless_chrome do |app|
  Capybara::Selenium::Driver.load_selenium
  browser_options = ::Selenium::WebDriver::Chrome::Options.new
  browser_options.args << '--headless'
  browser_options.args << '--disable-gpu'
  browser_options.args << '--allow-insecure-localhost'
  browser_options.args << '--no-sandbox'
  browser_options.args << '--window-size=1920,1080'
  Capybara::Selenium::Driver.new(app, browser: :chrome, options: browser_options)
end
```

For reference, the non-headless chrome (which works fine) is registered like this:
```
Capybara.register_driver :chrome do |app|
  Capybara::Selenium::Driver.new(app, :browser => :chrome)
end
```
I'm running this locally on OSX 10.14.4 for my Rails 5 app. 

#### Expected Behavior
Headless tests work and move to the next test. 

#### Actual Behavior
Here's the console when I try to run a test that doesn't move onto the next test:

```
Capybara starting Puma...
* Version 3.11.4 , codename: Love Song
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:3000
2019-05-14 08:55:08 WARN Webdrivers Driver caching is turned off in this version, but will be enabled by default in 4.x. Set the value with `Webdrivers#cache_time=` in seconds
  Scenario: X
    When X
2019-05-14 08:55:14 WARN Selenium [DEPRECATION] Selenium::WebDriver::Error::UnhandledError is deprecated. Use Selenium::WebDriver::Error::UnknownError (ensure the driver supports W3C WebDriver specification) instead.
2019-05-14 08:55:14 WARN Selenium [DEPRECATION] Selenium::WebDriver::Error::ElementNotVisibleError is deprecated. Use Selenium::WebDriver::Error::ElementNotInteractableError (ensure the driver supports W3C WebDriver specification) instead.
2019-05-14 08:55:14 WARN Selenium [DEPRECATION] Selenium::WebDriver::Error::InvalidElementStateError is deprecated. Use Selenium::WebDriver::Error::ElementNotInteractableError (ensure the driver supports W3C WebDriver specification) instead.
2019-05-14 08:55:14 WARN Selenium [DEPRECATION] Selenium::WebDriver::Error::ElementNotSelectableError is deprecated. Use Selenium::WebDriver::Error::ElementNotInteractableError (ensure the driver supports W3C WebDriver specification) instead.
2019-05-14 08:55:14 WARN Selenium [DEPRECATION] Selenium::WebDriver::Error::ElementNotSelectableError is deprecated. Use Selenium::WebDriver::Error::ElementNotInteractableError (ensure the driver supports W3C WebDriver specification) instead.
    Then X
2019-05-14 08:57:14 WARN Selenium [DEPRECATION] Selenium::WebDriver::Error::UnhandledError is deprecated. Use Selenium::WebDriver::Error::UnknownError (ensure the driver supports W3C WebDriver specification) instead.
2019-05-14 08:57:14 WARN Selenium [DEPRECATION] Selenium::WebDriver::Error::UnhandledAlertError is deprecated. Use Selenium::WebDriver::Error::UnexpectedAlertOpenError (ensure the driver supports W3C WebDriver specification) instead.
      Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
```

Edit: Whoops, and a minute or two after I sent this my terminal gave me a few more lines of errors:

```
  .rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/capybara-3.0.3/lib/capybara/selenium/driver.rb:50:in `block in browser'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/capybara-3.0.3/lib/capybara/selenium/driver.rb:269:in `quit'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/chrome/driver.rb:54:in `quit'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/common/driver.rb:168:in `quit'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/remote/oss/bridge.rb:136:in `quit'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/remote/oss/bridge.rb:587:in `execute'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/remote/http/default.rb:82:in `request'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/remote/http/default.rb:129:in `response_for'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/webmock-3.5.1/lib/webmock/http_lib_adapters/net_http.rb:104:in `request'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/webmock-3.5.1/lib/webmock/http_lib_adapters/net_http.rb:137:in `start_with_connect_without_finish'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/webmock-3.5.1/lib/webmock/http_lib_adapters/net_http.rb:105:in `block in request'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/webmock-3.5.1/lib/webmock/http_lib_adapters/net_http.rb:97:in `block in request'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/skylight-core-2.0.2/lib/skylight/core/probes/net_http.rb:47:in `request'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/skylight-core-2.0.2/lib/skylight/core/fanout.rb:25:in `instrument'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/skylight-core-2.0.2/lib/skylight/core/probes/net_http.rb:54:in `block in request'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/http.rb:1479:in `request'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/http.rb:1506:in `transport_request'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/http.rb:1506:in `catch'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/http.rb:1509:in `block in transport_request'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/http/response.rb:29:in `read_new'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/webmock-3.5.1/lib/webmock/http_lib_adapters/net_http.rb:284:in `rbuf_fill'
  .rbenv/versions/2.6.1/lib/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/capybara-3.0.3/lib/capybara/selenium/driver.rb:50:in `block in browser'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/capybara-3.0.3/lib/capybara/selenium/driver.rb:269:in `quit'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/chrome/driver.rb:56:in `quit'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/chrome/driver.rb:56:in `ensure in quit'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/common/service.rb:105:in `stop'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/common/service.rb:172:in `stop_server'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/common/service.rb:143:in `connect_to_server'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/http.rb:605:in `start'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/webmock-3.5.1/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/webmock-3.5.1/lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/common/service.rb:147:in `block in connect_to_server'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.2/lib/selenium/webdriver/common/service.rb:172:in `block in stop_server'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/http.rb:1228:in `get'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/webmock-3.5.1/lib/webmock/http_lib_adapters/net_http.rb:104:in `request'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/webmock-3.5.1/lib/webmock/http_lib_adapters/net_http.rb:137:in `start_with_connect_without_finish'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/webmock-3.5.1/lib/webmock/http_lib_adapters/net_http.rb:105:in `block in request'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/webmock-3.5.1/lib/webmock/http_lib_adapters/net_http.rb:97:in `block in request'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/skylight-core-2.0.2/lib/skylight/core/probes/net_http.rb:47:in `request'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/skylight-core-2.0.2/lib/skylight/core/fanout.rb:25:in `instrument'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/skylight-core-2.0.2/lib/skylight/core/probes/net_http.rb:54:in `block in request'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/http.rb:1479:in `request'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/http.rb:1506:in `transport_request'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/http.rb:1506:in `catch'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/http.rb:1509:in `block in transport_request'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/http/response.rb:29:in `read_new'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
	.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/webmock-3.5.1/lib/webmock/http_lib_adapters/net_http.rb:284:in `rbuf_fill'
	.rbenv/versions/2.6.1/lib/ruby/2.6.0/net/protocol.rb:210:in `rbuf_fill'
	 from <internal:prelude>:73:in `read_nonblock'
<internal:prelude>:73:in `__read_nonblock': Connection reset by peer (Errno::ECONNRESET)
```

**Comment by twalpole** [comment]
This gem only handles installation of the drivers, it has nothing else to do with configuring of Selenium. Also you need to update your Capybara to silence all those warnings. After that see https://github.com/teamcapybara/capybara/issues/2181

**Comment by BSierakowski** [comment]
Great, thanks—up and working from that issue.
