### ISSUE TITLE
Error with InsecureCommandExecution

### ISSUE THREAD

**Issue by utopianu** [titusfortner/webdrivers#125]
#### Summary
👋 I just switched to use 'webdrivers' gem for my system tests, however I'm seeing this error when it tries to update chromedriver

```
InsecureCommandExecution: insecure command execution via ` method from gems/webdrivers-4.0.0/lib/webdrivers/system.rb:150:in `call'
.../webdrivers-4.0.0/lib/webdrivers/system.rb:150:in `call'
.../webdrivers-4.0.0/lib/webdrivers/common.rb:144:in `binary_version'
.../webdrivers-4.0.0/lib/webdrivers/chromedriver.rb:18:in `current_version'
.../webdrivers-4.0.0/lib/webdrivers/common.rb:126:in `correct_binary?'
.../webdrivers-4.0.0/lib/webdrivers/common.rb:83:in `update'
```

#### Debug Info
Please provide the following information for bug reports:

* Operating system / CI Environment: MacOS 10.13/Debian 9
* Browser and version: Chrome 74

My headless Chrome config: 
```ruby
Capybara.register_driver(:headless_chrome) do |app|
    Capybara::Selenium::Driver.load_selenium
    capabilities = ::Selenium::WebDriver::Remote::Capabilities.chrome(
      chromeOptions: {args: ["headless", "disable-gpu", "window-size=1340,800",
        "--no-sandbox", "--allow-insecure-localhost",
        "--enable-features=NetworkService,NetworkServiceInProcess"]}
    )

    Capybara::Selenium::Driver.new(
      app,
      browser: :chrome,
      desired_capabilities: capabilities,
    )
  end
```

#### Actual Behavior
Debug Info: 
```
DEBUG Webdrivers Checking current version
DEBUG Webdrivers /.webdrivers/chromedriver is already downloaded
DEBUG Webdrivers making System call: /.webdrivers/chromedriver --version
DEBUG Webdrivers Checking current version
DEBUG Webdrivers /.webdrivers/chromedriver is already downloaded
DEBUG Webdrivers making System call: /.webdrivers/chromedriver --version
DEBUG Webdrivers Checking current version
DEBUG Webdrivers /.webdrivers/chromedriver is already downloaded
DEBUG Webdrivers making System call: /.webdrivers/chromedriver --version
DEBUG Webdrivers Checking current version
DEBUG Webdrivers /.webdrivers/chromedriver is already downloaded
DEBUG Webdrivers making System call: /.webdrivers/chromedriver --version
EDEBUG Webdrivers Checking current version
DEBUG Webdrivers /.webdrivers/chromedriver is already downloaded
DEBUG Webdrivers making System call: /.webdrivers/chromedriver --version
DEBUG Webdrivers Checking current version
DEBUG Webdrivers /.webdrivers/chromedriver is already downloaded
DEBUG Webdrivers making System call: /.webdrivers/chromedriver --version
```
Seems this code is throwing the errors, please let me how i can fix it 🙇‍♀ 
https://github.com/titusfortner/webdrivers/blob/07d518f077a6c415653f989e9365e94924e581c7/lib/webdrivers/common.rb#L144

**Comment by kapoorlakshya** [comment]
@utopianu Which version of Ruby are you using and was this on Mac or Debian, or both?

**Comment by twalpole** [comment]
What gem are you using that's producing the `InsecureCommandExecution` exception?

**Comment by kapoorlakshya** [comment]
@twalpole That is a good question. I couldn't find anything directly related to `InsecureCommandExecution` on Google. Was wondering if JRuby or some other flavor of Ruby was being used, but a gem raising that sounds more plausible.

**Comment by twalpole** [comment]
Closing due to lack of response.
