### ISSUE TITLE
session not created: This version of ChromeDriver only supports Chrome version 81 (Selenium::WebDriver::Error::SessionNotCreatedError)

### ISSUE THREAD

**Issue by madhan-kumaravel** [titusfortner/webdrivers#166]
#### Summary
I am using webdrivers gem to manage chromedriver. And this results in a version conflict.

#### Debug Info
* Webdrivers version:'3.9.4'
* Ruby version: 2.2.8p477
* Operating system / CI Environment:
* Browser and version: Chrome Version 80.0.3987.106 (Official Build) (64-bit)

#### Expected Behavior
Should launch chrome browser

#### Actual Behavior

```
0   chromedriver                        0x0000000105deb819 chromedriver + 4671513: session not created: This version of ChromeDriver only supports Chrome version 81 (Selenium::WebDriver::Error::SessionNotCreatedError)
	from 1   chromedriver                        0x0000000105d86663 chromedriver + 4257379
	from 2   chromedriver                        0x0000000105a3014f chromedriver + 758095
	from 3   chromedriver                        0x0000000105990189 chromedriver + 102793
	from 4   chromedriver                        0x000000010598c3bc chromedriver + 86972
	from 5   chromedriver                        0x00000001059bb5c3 chromedriver + 280003
	from 6   chromedriver                        0x00000001059b83d3 chromedriver + 267219
	from 7   chromedriver                        0x00000001059923dd chromedriver + 111581
	from 8   chromedriver                        0x0000000105993385 chromedriver + 115589
	from 9   chromedriver                        0x0000000105dae0cf chromedriver + 4419791
	from 10  chromedriver                        0x0000000105dbad6a chromedriver + 4472170
	from 11  chromedriver                        0x0000000105dbab07 chromedriver + 4471559
	from 12  chromedriver                        0x0000000105d92219 chromedriver + 4305433
	from 13  chromedriver                        0x0000000105dbb617 chromedriver + 4474391
	from 14  chromedriver                        0x0000000105da3e57 chromedriver + 4378199
	from 15  chromedriver                        0x0000000105dd1884 chromedriver + 4565124
	from 16  chromedriver                        0x0000000105df17a7 chromedriver + 4695975
	from 17  libsystem_pthread.dylib             0x00007fff5ce82661 _pthread_body + 340
	from 18  libsystem_pthread.dylib             0x00007fff5ce8250d _pthread_body + 0
	from 19  libsystem_pthread.dylib             0x00007fff5ce81bf9 thread_start + 13
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/bridge.rb:97:in `create_session'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/bridge.rb:53:in `handshake'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/chrome/driver.rb:47:in `initialize'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/common/driver.rb:44:in `new'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/common/driver.rb:44:in `for'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver.rb:86:in `for'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/capybara-3.1.1/lib/capybara/selenium/driver.rb:38:in `browser'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/capybara-3.1.1/lib/capybara/selenium/driver.rb:65:in `visit'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/capybara-3.1.1/lib/capybara/session.rb:273:in `visit'
	from base_class.rb:8:in `<class:BaseClass>'
	from base_class.rb:3:in `<main>'

```

**Comment by madhan-kumaravel** [comment]
Running for the second time (after chromedriver has downloaded) produces the following error.

```
/Users/madhan_kumaravel/.webdrivers/chromedriver
ChromeDriver 80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882})
/Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/webdrivers-3.0.0/lib/webdrivers/chromedriver.rb:14:in `current': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/webdrivers-3.0.0/lib/webdrivers/common.rb:13:in `update'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/webdrivers-3.0.0/lib/webdrivers/selenium.rb:7:in `driver_path'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/chrome/driver.rb:37:in `initialize'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/common/driver.rb:44:in `new'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/common/driver.rb:44:in `for'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver.rb:86:in `for'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/capybara-3.1.1/lib/capybara/selenium/driver.rb:38:in `browser'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/capybara-3.1.1/lib/capybara/selenium/driver.rb:65:in `visit'
	from /Users/madhan_kumaravel/.rvm/gems/ruby-2.2.8/gems/capybara-3.1.1/lib/capybara/session.rb:273:in `visit'
	from base_class.rb:8:in `<class:BaseClass>'
	from base_class.rb:3:in `<main>'
```

**Comment by madhan-kumaravel** [comment]
Somehow it's working now. So closing this ticket.
