### ISSUE TITLE
Webdrivers fails to download the latest Gecko WebDriver.

### ISSUE THREAD

**Issue by stefanvermaas** [titusfortner/webdrivers#210]
#### Summary

It seems the Mozilla team deviated from its default naming of releases for the Gecko WebDriver. This causes the automatic download of the WebDriver to fail. I've also opened up an issue at their repository because I'm not sure who's "mistake/problem" this is.

See https://github.com/mozilla/geckodriver/issues/1866

#### Debug info

```shell
Webdrivers::NetworkError: Net::HTTPServerException: 404 "Not Found" with https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-macos.tar.gz
/Users/stefan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/webdrivers-4.6.0/lib/webdrivers/network.rb:19:in `get'
/Users/stefan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/webdrivers-4.6.0/lib/webdrivers/system.rb:74:in `block (2 levels) in download_file'
/Users/stefan/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tempfile.rb:291:in `open'
```

* Webdrivers version: `v4.6.0`
* Ruby version: `v2.7.2`
* Operating system / CI Environment: `macOS`

#### Expected Behavior
To download the latest version of the Gecko driver.

#### Actual Behavior
It fails to download the latest version of the Gecko driver.

**Comment by titusfortner** [comment]
Thank you for reporting this both here and with geckodriver. Looks like they were able to quickly fix things as a result.
