### ISSUE TITLE
Errno::E086: Bad CPU type in executable

### ISSUE THREAD

**Issue by toomanyjoes** [titusfortner/webdrivers#216]
#### Summary
I've recently started seeing this error when I run my feature tests in rails using capybara and the geckodriver webdriver

``` 
Errno::E086:
       Bad CPU type in executable - /Users/rreynolds/.webdrivers/geckodriver
```

#### Debug Info

* Webdrivers version: 4.6.0 and 4.6.1
* Ruby version: 2.4
* Operating system / CI Environment: Big Sur 11.4
* Browser and version: Chrome Version 94.0.4606.54 (Official Build) (x86_64) 

#### Expected Behavior
Capybara feature tests should open up a firefox browser window and run. It has done this until very recently.

#### Actual Behavior

```
 Errno::E086:
       Bad CPU type in executable - /Users/rreynolds/.webdrivers/geckodriver
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/webdrivers-4.6.1/lib/webdrivers/system.rb:187:in `popen'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/webdrivers-4.6.1/lib/webdrivers/system.rb:187:in `call'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/webdrivers-4.6.1/lib/webdrivers/common.rb:152:in `binary_version'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/webdrivers-4.6.1/lib/webdrivers/geckodriver.rb:17:in `current_version'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/webdrivers-4.6.1/lib/webdrivers/common.rb:134:in `correct_binary?'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/webdrivers-4.6.1/lib/webdrivers/common.rb:91:in `update'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/webdrivers-4.6.1/lib/webdrivers/geckodriver.rb:72:in `block in <top (required)>'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/service.rb:133:in `binary_path'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/service.rb:94:in `initialize'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/service.rb:58:in `new'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/service.rb:58:in `firefox'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:299:in `service_url'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/firefox/marionette/driver.rb:38:in `initialize'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/firefox/driver.rb:33:in `new'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/firefox/driver.rb:33:in `new'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:54:in `for'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver.rb:88:in `for'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/capybara-3.32.0/lib/capybara/selenium/driver.rb:52:in `browser'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/capybara-3.32.0/lib/capybara/selenium/driver.rb:71:in `visit'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/capybara-3.32.0/lib/capybara/session.rb:278:in `visit'
     # /Users/rreynolds/.rvm/gems/ruby-2.4.1/gems/capybara-3.32.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
     # ./spec/support/feature_spec_helpers/sessions.rb:3:in `sign_in'
     # ./spec/features/client/choosing_session_loanset_spec.rb:8:in `block (2 levels) in <top (required)>'
```

**Comment by toomanyjoes** [comment]
Hmmm, I think I fixed it. I just deleted everything in ~/.webdrivers and then ran my specs again. The webdrivers gem seems to have redownloaded the geckodriver. Perhaps my binary got corrupted...
