### ISSUE TITLE
msedgedriver not resolved in Linux

### ISSUE THREAD

**Issue by bonigarcia** [titusfortner/webdrivers#236]
#### Summary
It seems there is a bug resolving msedgedriver in Linux.

#### Debug Info
* Webdrivers version: 5.0.0
* Ruby version: 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
* Operating system / CI Environment: Ubuntu 20.04.4 LTS
* Browser and version: 104.0.1293.54 (Official build) (64-bit)

#### Expected Behavior
The following script should pass:

```
# frozen_string_literal: true

RSpec.describe 'Install Drivers' do
  it 'edge session' do
    require 'webdrivers'

    Webdrivers.logger.level = :DEBUG
    
    driver = Selenium::WebDriver.for :edge

    driver.quit
  end
end
```

#### Actual Behavior
The error I get is the following:

```
  1) Install Drivers edge session
     Failure/Error: driver = Selenium::WebDriver.for :edge
     
     RuntimeError:
       Default location not yet known
     # /var/lib/gems/2.7.0/gems/webdrivers-5.0.0/lib/webdrivers/edge_finder.rb:83:in `linux_location'
     # /var/lib/gems/2.7.0/gems/webdrivers-5.0.0/lib/webdrivers/edge_finder.rb:18:in `location'
     # /var/lib/gems/2.7.0/gems/webdrivers-5.0.0/lib/webdrivers/edge_finder.rb:10:in `version'
     # /var/lib/gems/2.7.0/gems/webdrivers-5.0.0/lib/webdrivers/edgedriver.rb:17:in `browser_version'
     # /var/lib/gems/2.7.0/gems/webdrivers-5.0.0/lib/webdrivers/chromedriver.rb:135:in `browser_build_version'
     # /var/lib/gems/2.7.0/gems/webdrivers-5.0.0/lib/webdrivers/chromedriver.rb:32:in `latest_version'
     # /var/lib/gems/2.7.0/gems/webdrivers-5.0.0/lib/webdrivers/common.rb:122:in `download_version'
     # /var/lib/gems/2.7.0/gems/webdrivers-5.0.0/lib/webdrivers/common.rb:134:in `correct_binary?'
     # /var/lib/gems/2.7.0/gems/webdrivers-5.0.0/lib/webdrivers/common.rb:91:in `update'
     # /var/lib/gems/2.7.0/gems/webdrivers-5.0.0/lib/webdrivers/edgedriver.rb:104:in `block in <top (required)>'
     # /var/lib/gems/2.7.0/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/common/service.rb:101:in `binary_path'
     # /var/lib/gems/2.7.0/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/common/service.rb:73:in `initialize'
     # /var/lib/gems/2.7.0/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/common/service.rb:45:in `new'
     # /var/lib/gems/2.7.0/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/common/service.rb:45:in `edge'
     # /var/lib/gems/2.7.0/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/common/driver.rb:340:in `service_url'
     # /var/lib/gems/2.7.0/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/common/driver.rb:321:in `create_bridge'
     # /var/lib/gems/2.7.0/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
     # /var/lib/gems/2.7.0/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/common/driver.rb:55:in `new'
     # /var/lib/gems/2.7.0/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/common/driver.rb:55:in `for'
     # /var/lib/gems/2.7.0/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver.rb:89:in `for'
     # ./spec/getting_started/install_drivers_spec.rb:9:in `block (2 levels) in <top (required)>'
```

**Comment by titusfortner** [comment]
fixed in 5.1. Thanks.
