### ISSUE TITLE
Uncompressed geckodriver binary is 0 bytes

### ISSUE THREAD

**Issue by shepmaster** [titusfortner/webdrivers#3]
This manifests as a permission denied error:

```
  Errno::EACCES:
            Permission denied - /home/ubuntu/.webdrivers/geckodriver
```

I see that the file is zero bytes:

```
$ ls -l ~/.webdrivers/
total 2696
-rw-r--r--  1 shep  staff        0 Sep 13 16:36 geckodriver
-rw-r--r--  1 shep  staff  1378434 Sep 13 16:36 geckodriver-v0.18.0-macos.tar.gz
```

The MD5 of the downloaded file matches one I downloaded from GitHub by hand:

```
$ md5sum geckodriver-v0.18.0-macos.tar.gz /tmp/geckodriver-v0.18.0-macos.tar.gz
79cf3050cc942cdff6edbc7605d05ef2  geckodriver-v0.18.0-macos.tar.gz
79cf3050cc942cdff6edbc7605d05ef2  /tmp/geckodriver-v0.18.0-macos.tar.gz
```

And if I decompress it by hand, that also works:

```
$ tar -zxvf geckodriver-v0.18.0-macos.tar.gz
$ ls -lrt
total 10064
-rwxr-xr-x  1 shep  staff  3769184 Jul 11 08:49 geckodriver
-rw-r--r--  1 shep  staff  1378434 Sep 13 16:36 geckodriver-v0.18.0-macos.tar.gz
```

I am using webdrivers 3.2.1 with Ruby 2.3.3p222.

**Comment by shepmaster** [comment]
This occurs on both macOS and Linux.

**Comment by shepmaster** [comment]
This code appears to decompress the file as expected:

```ruby
      def untargz_file(filename)
        tar_extract = Gem::Package::TarReader.new(Zlib::GzipReader.open(filename))

        File.open(file_name, "w+b") do |ucf|
          tar_extract.each {|entry| ucf << entry.read}
          File.basename ucf
        end
      end
```

Notable changes; I'm uncertain which specific change fixed it:

1. No `rewind` call — not sure what it's for, but presumably a freshly-opened file should already be at the start.
1. Added `b` to the flags. This is my best guess as to the fix. [Otherwise the encodings of the data probably don't match](https://stackoverflow.com/a/11770507/155423).
1. Switched to the block-form of `File.open` to ensure the file is closed even in case of an exception.

**Comment by shepmaster** [comment]
You may also want to enhance your test that ensures that the driver is downloaded to also check that it's runnable or at least non-zero size.

**Comment by shepmaster** [comment]
> Added b to the flags. This is my best guess as to the fix.

Ah, yes; I found this exception hidden in my test log:

```
          Encoding::UndefinedConversionError:
            "\xCF" from ASCII-8BIT to UTF-8
          # /Users/shep/.rvm/gems/ruby-2.3.3@checklistpro/gems/webdrivers-3.2.1/lib/webdrivers/common.rb:146:in `write'
          # /Users/shep/.rvm/gems/ruby-2.3.3@checklistpro/gems/webdrivers-3.2.1/lib/webdrivers/common.rb:146:in `<<'
          # /Users/shep/.rvm/gems/ruby-2.3.3@checklistpro/gems/webdrivers-3.2.1/lib/webdrivers/common.rb:146:in `block in untargz_file'
          # /Users/shep/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/package/tar_reader.rb:65:in `each'
          # /Users/shep/.rvm/gems/ruby-2.3.3@checklistpro/gems/webdrivers-3.2.1/lib/webdrivers/common.rb:146:in `untargz_file'
          # /Users/shep/.rvm/gems/ruby-2.3.3@checklistpro/gems/webdrivers-3.2.1/lib/webdrivers/common.rb:127:in `decompress_file'
          # /Users/shep/.rvm/gems/ruby-2.3.3@checklistpro/gems/webdrivers-3.2.1/lib/webdrivers/common.rb:37:in `block in download'
          # /Users/shep/.rvm/gems/ruby-2.3.3@checklistpro/gems/webdrivers-3.2.1/lib/webdrivers/common.rb:30:in `chdir'
          # /Users/shep/.rvm/gems/ruby-2.3.3@checklistpro/gems/webdrivers-3.2.1/lib/webdrivers/common.rb:30:in `download'
          # /Users/shep/.rvm/gems/ruby-2.3.3@checklistpro/gems/webdrivers-3.2.1/lib/webdrivers/common.rb:13:in `update'
          # /Users/shep/.rvm/gems/ruby-2.3.3@checklistpro/gems/webdrivers-3.2.1/lib/webdrivers/selenium.rb:13:in `driver_path'
          # /Users/shep/.rvm/gems/ruby-2.3.3@checklistpro/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/firefox/marionette/driver.rb:39:in `initialize'
          # /Users/shep/.rvm/gems/ruby-2.3.3@checklistpro/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/firefox/driver.rb:33:in `new'
          # /Users/shep/.rvm/gems/ruby-2.3.3@checklistpro/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/firefox/driver.rb:33:in `new'
          # /Users/shep/.rvm/gems/ruby-2.3.3@checklistpro/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver/common/driver.rb:54:in `for'
          # /Users/shep/.rvm/gems/ruby-2.3.3@checklistpro/gems/selenium-webdriver-3.5.2/lib/selenium/webdriver.rb:86:in `for'
          # /Users/shep/.rvm/gems/ruby-2.3.3@checklistpro/gems/capybara-2.15.1/lib/capybara/selenium/driver.rb:23:in `browser'
          # ./spec/rails_helper.rb:129:in `block (2 levels) in <top (required)>'
```
