### ISSUE TITLE
DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by christianmkuss** [titusfortner/webdrivers#63]
I am not sure if this directly an issue with chromedriver or selenium or anything else. I am currently running my program in docker (which uses Debian 9.5) with ruby:2.5.1. I am able to install chrome directly and can confirm the download with `google-chrome --version` which yields `73.0.3683.103`. 

I have confirmed that the path is `/usr/bin/google-chrome` and have set it directly with `Selenium::WebDriver::Chrome.path = '/usr/bin/google-chrome'` to ensure it is locating Chrome correctly.

This is the error I am getting
```
Selenium::WebDriver::Error::UnknownError:
       unknown error: Chrome failed to start: exited abnormally
         (unknown error: DevToolsActivePort file doesn't exist)
         (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
         (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.9.125-linuxkit x86_64)
     # /usr/local/bundle/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
     # /usr/local/bundle/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
     # /usr/local/bundle/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
     # /usr/local/bundle/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
     # /usr/local/bundle/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
     # /usr/local/bundle/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
     # /usr/local/bundle/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:166:in `execute'
     # /usr/local/bundle/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:99:in `create_session'
     # /usr/local/bundle/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:53:in `handshake'
     # /usr/local/bundle/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/chrome/driver.rb:49:in `initialize'
     # /usr/local/bundle/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/driver.rb:44:in `new'
     # /usr/local/bundle/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/driver.rb:44:in `for'
     # /usr/local/bundle/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver.rb:86:in `for'
     # /usr/local/bundle/gems/capybara-3.16.1/lib/capybara/selenium/driver.rb:37:in `browser'
     # /usr/local/bundle/gems/capybara-3.16.1/lib/capybara/selenium/driver.rb:56:in `visit'
     # /usr/local/bundle/gems/capybara-3.16.1/lib/capybara/session.rb:277:in `visit'
     # /usr/local/bundle/gems/capybara-3.16.1/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'```

**Comment by christianmkuss** [comment]
So not sure if this is the best way to fix it but I got around it by using 
```Capybara.register_driver :chrome do |app|
      Capybara::Selenium::Driver.new(
        app,
        browser: :chrome,
        args: %w[--no-sandbox --headless]
      )
    end```
Which currently throws a deprecation warning. But it at least starts Chrome.

Closing the issue.

**Comment by christianmkuss** [comment]
In case anyone needs it.
```
Capybara.register_driver :chrome do |app|
Capybara::Selenium::Driver.new app,browser: :chrome,
    options: Selenium::WebDriver::Chrome::Options.new(args: %w[--no-sandbox --headless])
end
Capybara.javascript_driver = :chrome
```
