### ISSUE TITLE
invalid chromedriver for alpine

### ISSUE THREAD

**Issue by kinnalru** [titusfortner/webdrivers#78]
On Alpine linux webdrivers gem downloads invalid binary. This binary has strange error when executing:
```
@0fb37473e04b:~/.webdrivers$ ./chromedriver --help
/bin/ash: ./chromedriver: not found
```

From within irb:
```
irb(main):034:0> File.exists?('/root/.webdrivers/chromedriver')
=> true
irb(main):035:0> Webdrivers::Chromedriver.current_version      
2019-04-29 11:25:40 DEBUG Webdrivers Checking current version
2019-04-29 11:25:40 DEBUG Webdrivers File is already downloaded: true
/usr/local/bundle/bin/bundle: No such file or directory - /root/.webdrivers/chromedriver
2019-04-29 11:25:40 DEBUG Webdrivers Current /root/.webdrivers/chromedriver version: 
Traceback (most recent call last):
       15: from /usr/local/bundle/bin/bundle:23:in `<main>'
       14: from /usr/local/bundle/bin/bundle:23:in `load'
       13: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
       12: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
       11: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
       10: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'
        9: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
        8: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
        7: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
        6: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        5: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        4: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:494:in `console'
        3: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/console.rb:19:in `run'
        2: from (irb):35
        1: from /usr/local/bundle/gems/webdrivers-3.8.0/lib/webdrivers/chromedriver.rb:15:in `current_version'
```

Reason(ldd output): 
```
@0fb37473e04b:~/.webdrivers$ ldd ./chromedriver
        /lib64/ld-linux-x86-64.so.2 (0x7fa23b37c000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7fa23b37c000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fa23b37c000)
        librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7fa23b37c000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x7fa23a818000)
        libnss3.so => /usr/lib/libnss3.so (0x7fa23a6ea000)
        libnssutil3.so => /usr/lib/libnssutil3.so (0x7fa23a6b8000)
        libnspr4.so => /usr/lib/libnspr4.so (0x7fa23a676000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x7fa23a553000)
        libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fa23b37c000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fa23a53f000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fa23b37c000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by ./chromedriver)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x7fa23a4e2000)
        libintl.so.8 => /usr/lib/libintl.so.8 (0x7fa23a4d2000)
        libplc4.so => /usr/lib/libplc4.so (0x7fa23a4cb000)
        libplds4.so => /usr/lib/libplds4.so (0x7fa23a4c6000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x7fa23a49f000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x7fa23a49a000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x7fa23a492000)
        libbsd.so.0 => /usr/lib/libbsd.so.0 (0x7fa23a47e000)
```

chromium-chromedriver downloaded through apline package manger works well.

**Comment by kapoorlakshya** [comment]
Hi @kinnalru, I Googled the error in the Idd output (`Error loading shared library ld-linux-x86-64.so.2`) and found this possible solution - https://stackoverflow.com/questions/50288034/unsatisfiedlinkerror-tmp-snappy-1-1-4-libsnappyjava-so-error-loading-shared-li/51655643#51655643

Did you already give this a try?

**Comment by twalpole** [comment]
This gem downloads the official Google released versions of chromedriver from http://chromedriver.chromium.org/downloads.  If those aren't compatible with the OS you're using then this gem isn't going to work for you.

**Comment by bobvanderlinden** [comment]
Same issue here on NixOS. The official binary is made to run on Ubuntu/Debian:

```
$ ldd ~/.webdrivers/chromedriver
	linux-vdso.so.1 (0x00007ff731893000)
	libdl.so.2 => /nix/store/gafigwfaimlziam6qhw1m8dz4h952g1n-glibc-2.32-35/lib/libdl.so.2 (0x00007ff730d50000)
	libpthread.so.0 => /nix/store/gafigwfaimlziam6qhw1m8dz4h952g1n-glibc-2.32-35/lib/libpthread.so.0 (0x00007ff730d2f000)
	librt.so.1 => /nix/store/gafigwfaimlziam6qhw1m8dz4h952g1n-glibc-2.32-35/lib/librt.so.1 (0x00007ff730d24000)
	libglib-2.0.so.0 => not found
	libnss3.so => not found
	libnssutil3.so => not found
	libnspr4.so => not found
	libm.so.6 => /nix/store/gafigwfaimlziam6qhw1m8dz4h952g1n-glibc-2.32-35/lib/libm.so.6 (0x00007ff730bdf000)
	libxcb.so.1 => not found
	libgcc_s.so.1 => /nix/store/gafigwfaimlziam6qhw1m8dz4h952g1n-glibc-2.32-35/lib/libgcc_s.so.1 (0x00007ff730bc5000)
	libc.so.6 => /nix/store/gafigwfaimlziam6qhw1m8dz4h952g1n-glibc-2.32-35/lib/libc.so.6 (0x00007ff730a04000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/gafigwfaimlziam6qhw1m8dz4h952g1n-glibc-2.32-35/lib64/ld-linux-x86-64.so.2 (0x00007ff731895000)
```
It would be nice if we could specify a environment variable to direct webdrivers to the right chromedriver binary, as I already have it installed. Alternatively it could check `PATH`.

**Comment by kapoorlakshya** [comment]
@bobvanderlinden Selenium does look at `PATH` to find the drivers ([source](https://www.selenium.dev/documentation/en/webdriver/driver_requirements/)). In your case, the path forward would be to stop using `webdrivers` and let Selenium pick up whichever `chromedriver` binary you want from `PATH`.

**Comment by woto** [comment]
For those who struggle with the same problem:
Try this:

```
  # gem 'webdrivers'                                         
  gem 'selenium'                                               
```

At least it helped to me.

**Comment by schadenfred** [comment]
For me it worked on alpine in docker by commenting out webdrivers gem similar to https://github.com/titusfortner/webdrivers/issues/78#issuecomment-960120737
