### ISSUE TITLE
`block in newest_version': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by louise-r-blue** [titusfortner/webdrivers#89]
#### Summary
I have failing cucumber tests locally and in Codeship build after migrating from the `chromedriver-helper` gem to the `webdrivers` gem. The error is ` unable to connect to chromedriver 127.0.0.1:9515 (Selenium::WebDriver::Error::WebDriverError)`

The 'newest_version` in the title refers to the method in the webdrivers/chromedriver.rb 

```
  def newest_version
        padded = downloads.keys.each_with_object({}) do |version, hash|
          matched = version.match(/^(\d+)\.(\d+)$/)
          minor = sprintf '%02d', matched[2]
          hash["#{matched[1]}.#{minor}"] = version
        end
        padded.keys.sort.last
   end
```

I have gems to update due to security vulnerabilities and your help much appreciated.

#### Info

Outside the project directory running `chromedriver --version` 

```
Starting ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}) on port 9515
```

In the project directory that I need to update running `chromedriver --version` traceback

```
Traceback (most recent call last):
        8: from /Users/louiserobinson-blue/.rbenv/versions/2.5.3/bin/chromedriver:23:in `<main>'
        7: from /Users/louiserobinson-blue/.rbenv/versions/2.5.3/bin/chromedriver:23:in `load'
        6: from /Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webdrivers-2.4.0/bin/chromedriver:5:in `<top (required)>'
        5: from /Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webdrivers-2.4.0/lib/webdrivers/common.rb:9:in `install'
        4: from /Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webdrivers-2.4.0/lib/webdrivers/common.rb:16:in `download'
        3: from /Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webdrivers-2.4.0/lib/webdrivers/chromedriver.rb:17:in `newest_version'
        2: from /Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webdrivers-2.4.0/lib/webdrivers/chromedriver.rb:17:in `each_with_object'
        1: from /Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webdrivers-2.4.0/lib/webdrivers/chromedriver.rb:17:in `each'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webdrivers-2.4.0/lib/webdrivers/chromedriver.rb:19:in `block in newest_version': undefined method `[]' for nil:NilClass (NoMethodError)
```

* Operating system
Mac IOS 

#### Actual Behavior with logger and running `bundle exec cucumber`
```
undefined method `logger' for Webdrivers:Module (NoMethodError)
/Users/louiserobinson-blue/Documents/workplace/nznavigator/features/support/capybara.rb:3:in `<top (required)>'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:268:in `load'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:268:in `block in load'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:268:in `load'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/glue/registry_and_more.rb:106:in `load_code_file'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/runtime/support_code.rb:147:in `load_file'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/runtime/support_code.rb:88:in `block in load_files!'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/runtime/support_code.rb:87:in `each'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/runtime/support_code.rb:87:in `load_files!'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/runtime.rb:270:in `load_step_definitions'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/runtime.rb:67:in `run!'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/cli/main.rb:33:in `execute!'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/bin/cucumber:9:in `<top (required)>'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/bin/cucumber:23:in `load'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/bin/cucumber:23:in `<top (required)>'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/bin/bundle:23:in `load'
/Users/louiserobinson-blue/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'
```

I have the logger in the capybara.rb
```
require "selenium/webdriver"
require "webdrivers"
Webdrivers.logger.level = :DEBUG

Capybara.register_driver :chrome do |app|
  Capybara::Selenium::Driver.new(app, browser: :chrome)
end

Capybara.register_driver :headless_chrome do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
    chromeOptions: { args: %w[headless disable-gpu] }
  )

  Capybara::Selenium::Driver.new app,
    browser: :chrome,
    desired_capabilities: capabilities
end

Capybara.javascript_driver = :headless_chrome
```

**Comment by kapoorlakshya** [comment]
Hi @louise-r-blue, I see that you are using v2.4.0 of this gem based on the stack trace. I recommend upgrading to the latest version (3.8.0) and then trying to reproduce this. Chances are upgrading will solve this problem.

**Comment by titusfortner** [comment]
Version 2 of the driver creates a shim on the system, which we want to avoid. Please make sure you uninstall the gem, and then delete the shims from the system. 

Version 3.x injects the necessary behavior into the Selenium code itself without affecting the system.

Let us know if that does not address your issue.

**Comment by louise-r-blue** [comment]
Thanks. All good now
